"""add shown flag to candidate matches

Revision ID: 0a66ebe386d6
Revises: 6cd1d4e6aaaf
Create Date: 2026-07-08 22:23:41.253895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a66ebe386d6'
down_revision: Union[str, None] = '6cd1d4e6aaaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "candidate_matches",
        sa.Column("shown", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_matches', 'shown')
    # ### end Alembic commands ###
