"""discovery and resolution tables

Revision ID: 1a634df3f7be
Revises: 14ae022ce10a
Create Date: 2026-07-08 22:07:18.556326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a634df3f7be'
down_revision: Union[str, None] = '14ae022ce10a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_developers_name'), 'developers', ['name'], unique=False)
    op.create_table('ranking_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('auto_proceed_threshold', sa.Float(), nullable=False),
    sa.Column('show_threshold', sa.Float(), nullable=False),
    sa.Column('separation_margin', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canonical_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('developer_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('rera_registration_number', sa.String(length=100), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('locality', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state', 'rera_registration_number', 'developer_id', 'project_name')
    )
    op.create_index(op.f('ix_canonical_projects_city'), 'canonical_projects', ['city'], unique=False)
    op.create_index(op.f('ix_canonical_projects_project_name'), 'canonical_projects', ['project_name'], unique=False)
    op.create_table('search_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.String(length=255), nullable=False),
    sa.Column('normalized_text', sa.String(length=255), nullable=False),
    sa.Column('city_hint', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_queries_normalized_text'), 'search_queries', ['normalized_text'], unique=False)
    op.create_table('candidate_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_query_id', sa.UUID(), nullable=False),
    sa.Column('canonical_project_id', sa.UUID(), nullable=False),
    sa.Column('score_exact_name', sa.Float(), nullable=False),
    sa.Column('score_fuzzy_name', sa.Float(), nullable=False),
    sa.Column('score_city', sa.Float(), nullable=True),
    sa.Column('score_historical_selection', sa.Float(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('chosen', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_project_id'], ['canonical_projects.id'], ),
    sa.ForeignKeyConstraint(['search_query_id'], ['search_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('confirmed_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('normalized_search_string', sa.String(length=255), nullable=False),
    sa.Column('city_hint', sa.String(length=100), nullable=True),
    sa.Column('canonical_project_id', sa.UUID(), nullable=False),
    sa.Column('confidence_at_confirmation', sa.Float(), nullable=False),
    sa.Column('confirmed_by', sa.UUID(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_project_id'], ['canonical_projects.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_search_string', 'city_hint')
    )
    op.create_index(op.f('ix_confirmed_mappings_normalized_search_string'), 'confirmed_mappings', ['normalized_search_string'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_confirmed_mappings_normalized_search_string'), table_name='confirmed_mappings')
    op.drop_table('confirmed_mappings')
    op.drop_table('candidate_matches')
    op.drop_index(op.f('ix_search_queries_normalized_text'), table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_index(op.f('ix_canonical_projects_project_name'), table_name='canonical_projects')
    op.drop_index(op.f('ix_canonical_projects_city'), table_name='canonical_projects')
    op.drop_table('canonical_projects')
    op.drop_table('ranking_configs')
    op.drop_index(op.f('ix_developers_name'), table_name='developers')
    op.drop_table('developers')
    # ### end Alembic commands ###
