"""manual override detail and field review flag

Revision ID: 77efabe20895
Revises: e4968392de52
Create Date: 2026-07-08 23:39:42.799938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77efabe20895'
down_revision: Union[str, None] = 'e4968392de52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_override_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data_point_id', sa.UUID(), nullable=False),
    sa.Column('overridden_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_point_id'], ['data_points.id'], ),
    sa.ForeignKeyConstraint(['overridden_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_point_id')
    )
    op.add_column(
        'field_catalog',
        sa.Column('requires_override_review', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field_catalog', 'requires_override_review')
    op.drop_table('manual_override_details')
    # ### end Alembic commands ###
