"""analytics assumption sets and forecast runs

Revision ID: acd6d9d84c26
Revises: 8c70a446a687
Create Date: 2026-07-14 22:26:31.320569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acd6d9d84c26'
down_revision: Union[str, None] = '8c70a446a687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_assumption_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('engine_type', sa.Enum('PRICING', 'SALES_VELOCITY', 'FINANCIAL', 'RISK', name='engine_type'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_project_id', sa.UUID(), nullable=False),
    sa.Column('engine_type', sa.Enum('PRICING', 'SALES_VELOCITY', 'FINANCIAL', 'RISK', name='engine_type'), nullable=False),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('assumption_set_id', sa.UUID(), nullable=False),
    sa.Column('input_manifest', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'INSUFFICIENT_DATA', name='forecast_run_status'), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assumption_set_id'], ['analytics_assumption_sets.id'], ),
    sa.ForeignKeyConstraint(['canonical_project_id'], ['canonical_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecast_runs')
    op.drop_table('analytics_assumption_sets')
    # ### end Alembic commands ###
