"""acquisition tables

Revision ID: b762954c8571
Revises: 0a66ebe386d6
Create Date: 2026-07-08 22:46:08.277386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b762954c8571'
down_revision: Union[str, None] = '0a66ebe386d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('RERA', 'DEVELOPER_SITE', 'MARKET_DATA', 'INFRASTRUCTURE', 'NEWS', 'GOVERNMENT_DATA', 'MANUAL_OVERRIDE', name='source_type'), nullable=False),
    sa.Column('adapter_key', sa.String(length=100), nullable=False),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('base_confidence', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('legal_review_signed_off', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_catalog',
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('value_type', sa.Enum('TEXT', 'NUMERIC', 'DATE', 'JSON', name='data_point_value_type'), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('source_priority', sa.JSON(), nullable=False),
    sa.Column('staleness_threshold_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('field_name')
    )
    op.create_table('acquisition_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_project_id', sa.UUID(), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', 'SKIPPED', name='acquisition_run_status'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['canonical_project_id'], ['canonical_projects.id'], ),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('value_type', sa.Enum('TEXT', 'NUMERIC', 'DATE', 'JSON', name='data_point_value_type'), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_numeric', sa.Float(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUPERSEDED', 'CORROBORATED', 'CONFLICTING', 'OVERRIDDEN', 'REJECTED', name='data_point_status'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('acquisition_run_id', sa.UUID(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_confidence', sa.Float(), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('composite_confidence', sa.Float(), nullable=False),
    sa.Column('previous_data_point_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acquisition_run_id'], ['acquisition_runs.id'], ),
    sa.ForeignKeyConstraint(['previous_data_point_id'], ['data_points.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_points_entity_id'), 'data_points', ['entity_id'], unique=False)
    op.create_index(op.f('ix_data_points_entity_type'), 'data_points', ['entity_type'], unique=False)
    op.create_index(op.f('ix_data_points_field_name'), 'data_points', ['field_name'], unique=False)
    op.create_table('conflict_resolution_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('winning_data_point_id', sa.UUID(), nullable=False),
    sa.Column('losing_data_point_id', sa.UUID(), nullable=False),
    sa.Column('rule_applied', sa.String(length=255), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['losing_data_point_id'], ['data_points.id'], ),
    sa.ForeignKeyConstraint(['winning_data_point_id'], ['data_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conflict_resolution_logs')
    op.drop_index(op.f('ix_data_points_field_name'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_entity_type'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_entity_id'), table_name='data_points')
    op.drop_table('data_points')
    op.drop_table('acquisition_runs')
    op.drop_table('field_catalog')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
